
DROP TABLE ATTACHMENT;
DROP TABLE REPLY;
DROP TABLE BOARD;
DROP TABLE CATEGORY;
DROP TABLE NOTICE;
DROP TABLE MEMBER;

DROP SEQUENCE SEQ_UNO;
DROP SEQUENCE SEQ_NNO;
DROP SEQUENCE SEQ_BID;
DROP SEQUENCE SEQ_RID;
DROP SEQUENCE SEQ_FID;

--------------------------------------------------
--------------     MEMBER 관련	------------------	
--------------------------------------------------

CREATE TABLE MEMBER (
  USER_NO NUMBER PRIMARY KEY,
  USER_ID VARCHAR2(30) NOT NULL,
  USER_PWD VARCHAR2(100) NOT NULL,
  USER_NAME VARCHAR2(15) NOT NULL,
  PHONE VARCHAR2(13),
  EMAIL VARCHAR2(100),
  ADDRESS VARCHAR2(100),
  INTEREST VARCHAR2(100),
  ENROLL_DATE DATE DEFAULT SYSDATE,
  MODIFY_DATE DATE DEFAULT SYSDATE,
  STATUS VARCHAR2(1) DEFAULT 'Y'
);

CREATE SEQUENCE SEQ_UNO;

INSERT INTO MEMBER 
VALUES (SEQ_UNO.NEXTVAL, 'admin', '1234', '관리자', '010-1111-2222', 'admin@kh.or.kr', '서울시 강남구 역삼동', NULL, SYSDATE, SYSDATE, DEFAULT);

INSERT INTO MEMBER 
VALUES (SEQ_UNO.NEXTVAL, 'user01', 'pass01', '홍길동', '010-3333-4444', 'user01@kh.or.kr', '서울시 양천구 목동', NULL, SYSDATE, SYSDATE, DEFAULT);

COMMIT;

--------------------------------------------------
--------------     NOTICE 관련	-------------------
--------------------------------------------------

CREATE TABLE NOTICE(
  NNO NUMBER PRIMARY KEY,
  NTITLE VARCHAR2(100) NOT NULL,
  NCONTENT VARCHAR2(4000) NOT NULL,
  NWRITER VARCHAR2(30) NOT NULL,
  NCOUNT NUMBER DEFAULT 0,
  NDATE DATE DEFAULT SYSDATE,
  STATUS VARCHAR2(1) DEFAULT 'Y'
);

CREATE SEQUENCE SEQ_NNO;

INSERT INTO NOTICE
VALUES (SEQ_NNO.NEXTVAL, '첫번째 공지사항입니다.', '환영합니다.', 'admin', DEFAULT, SYSDATE, DEFAULT);

COMMIT;

----------------------------------------------------
----------  CATEGORY 관련 (BOARD의 CID와 연관)  ----------	
----------------------------------------------------

CREATE TABLE CATEGORY(
  CID NUMBER PRIMARY KEY,
  CNAME VARCHAR2(30) CHECK(CNAME IN('공통', '운동', '등산', '게임', '낚시', '요리', '기타'))  
);

INSERT INTO CATEGORY VALUES(10, '공통');
INSERT INTO CATEGORY VALUES(20, '운동');
INSERT INTO CATEGORY VALUES(30, '등산');
INSERT INTO CATEGORY VALUES(40, '게임');
INSERT INTO CATEGORY VALUES(50, '낚시');
INSERT INTO CATEGORY VALUES(60, '요리');
INSERT INTO CATEGORY VALUES(70, '기타');

COMMIT;

----------------------------------------------------
----------------     BOARD 관련            -----------------	
----------------------------------------------------

CREATE TABLE BOARD(
  BID NUMBER PRIMARY KEY,
  BTYPE NUMBER, -- 일반 게시판(1)이냐 사진 게시판(2)이냐
  CID NUMBER,
  BTITLE VARCHAR2(100),
  BCONTENT VARCHAR2(4000),
  BWRITER NUMBER,
  BCOUNT NUMBER DEFAULT 0,
  CREATE_DATE DATE,
  MODIFY_DATE DATE,
  STATUS VARCHAR2(1) DEFAULT 'Y' CHECK (STATUS IN('Y', 'N')),
  FOREIGN KEY (BWRITER) REFERENCES MEMBER,
  FOREIGN KEY (CID) REFERENCES CATEGORY
);

CREATE SEQUENCE SEQ_BID;

-- BOARD 조회용 쿼리문 관련 

-- 1. BOARD 리스트 BID 내림차순 정렬 기준 
SELECT BID, BTYPE, CNAME, BTITLE, BCONTENT, USER_NAME, BCOUNT, B.CREATE_DATE, B.MODIFY_DATE, B.STATUS
FROM BOARD B
JOIN MEMBER M ON(B.BWRITER = M.USER_NO)
JOIN CATEGORY C ON(B.CID = C.CID)
WHERE B.STATUS = 'Y'
ORDER BY BID DESC;

-- 2. 인라인 뷰 ROWNUM 활용   --> 리스트 출력시 이용 계획
SELECT *
FROM (SELECT ROWNUM RNUM, BID, BTYPE, CNAME, BTITLE, BCONTENT, USER_NAME, BCOUNT, CREATE_DATE, MODIFY_DATE, STATUS
      FROM (SELECT BID, BTYPE, CNAME, BTITLE, BCONTENT, USER_NAME, BCOUNT, B.CREATE_DATE, B.MODIFY_DATE, B.STATUS
            FROM BOARD B
            JOIN MEMBER M ON(B.BWRITER = M.USER_NO)
            JOIN CATEGORY C ON(B.CID = C.CID)
            WHERE B.STATUS = 'Y'
            ORDER BY BID DESC))
WHERE BTYPE = 1 AND RNUM BETWEEN 11 AND 20;

-- 3. BOARD 상세보기시 이용 계획
SELECT BID, BTYPE, CNAME, BTITLE, BCONTENT, USER_NAME, BCOUNT, B.CREATE_DATE, B.MODIFY_DATE, B.STATUS
FROM BOARD B
JOIN MEMBER M ON(B.BWRITER = M.USER_NO)
JOIN CATEGORY C ON(B.CID = C.CID)
WHERE B.STATUS = 'Y' AND BID=1;


----------------------------------------------------
---------------     REPLY 관련         -------------------	
----------------------------------------------------

CREATE TABLE REPLY(
  RID NUMBER PRIMARY KEY,
  RCONTENT VARCHAR2(400),
  REF_BID NUMBER,
  RWRITER NUMBER,
  CREATE_DATE DATE,
  MODIFY_DATE DATE,
  STATUS VARCHAR2(1) DEFAULT 'Y' CHECK (STATUS IN ('Y', 'N')),
  FOREIGN KEY (REF_BID) REFERENCES BOARD,
  FOREIGN KEY (RWRITER) REFERENCES MEMBER
);

CREATE SEQUENCE SEQ_RID;

-- 한 게시판에 해당하는 댓글 리스트 조회용 쿼리문
SELECT RID, RCONTENT, REF_BID, USER_NAME, R.CREATE_DATE, R.MODIFY_DATE, R.STATUS
FROM REPLY R
JOIN MEMBER M ON(R.RWRITER = M.USER_NO)
WHERE R.STATUS='Y' AND REF_BID = 1
ORDER BY RID DESC;

----------------------------------------------------
--------------     ATTACHMENT 관련             --------------	
----------------------------------------------------

CREATE TABLE ATTACHMENT (
  FID NUMBER PRIMARY KEY,
  BID NUMBER NOT NULL,
  ORIGIN_NAME VARCHAR2(255) NOT NULL,
  CHANGE_NAME VARCHAR2(255) NOT NULL,
  FILE_PATH VARCHAR2(1000) NOT NULL,
  UPLOAD_DATE DATE DEFAULT SYSDATE,
  FILE_LEVEL NUMBER,
  DOWNLOAD_COUNT NUMBER DEFAULT 0,
  STATUS VARCHAR2(1) DEFAULT 'Y',
  FOREIGN KEY (BID) REFERENCES BOARD 
);

CREATE SEQUENCE SEQ_FID;

COMMIT;


