-- BOARD 리스트 조회용 VIEW - BLIST 
CREATE OR REPLACE VIEW BLIST 
AS 
SELECT ROWNUM RNUM, BID, BTYPE, CNAME, BTITLE, BCONTENT, USER_NAME, BCOUNT, CREATE_DATE, MODIFY_DATE, STATUS
FROM (SELECT BID, BTYPE, CNAME, BTITLE, BCONTENT, USER_NAME, BCOUNT, B.CREATE_DATE, B.MODIFY_DATE, B.STATUS
      FROM BOARD B
      JOIN MEMBER M ON(B.BWRITER = M.USER_NO)
      JOIN CATEGORY C ON(B.CID = C.CID)
      WHERE B.STATUS = 'Y'
      ORDER BY BID DESC);
      
-- BOARD 상세보기용 VIEW - BDETAIL
CREATE OR REPLACE VIEW BDETAIL 
AS
SELECT BID, BTYPE, CNAME, BTITLE, BCONTENT, USER_NAME, BCOUNT, B.CREATE_DATE, B.MODIFY_DATE, B.STATUS
FROM BOARD B
JOIN MEMBER M ON(B.BWRITER = M.USER_NO)
JOIN CATEGORY C ON(B.CID = C.CID)
WHERE B.STATUS = 'Y';

-- REPLY 리스트 조회용 VIEW - RLIST
CREATE OR REPLACE VIEW RLIST
AS
SELECT RID, RCONTENT, REF_BID, USER_NAME, R.CREATE_DATE, R.MODIFY_DATE, R.STATUS
FROM REPLY R
JOIN MEMBER M ON(R.RWRITER = M.USER_NO)
WHERE R.STATUS='Y'
ORDER BY RID DESC;